[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
PORT = { default = "8000" }
APP_ENV = { default = "production" }
APP_DEBUG = { default = "false" }
DB_CONNECTION = { default = "pgsql" }
DB_HOST = { default = "${{ POSTGRES_HOST }}" }
DB_PORT = { default = "${{ POSTGRES_PORT }}" }
DB_DATABASE = { default = "${{ POSTGRES_DB }}" }
DB_USERNAME = { default = "${{ POSTGRES_USER }}" }
DB_PASSWORD = { default = "${{ POSTGRES_PASSWORD }}" }
DATABASE_URL = { default = "${{ DATABASE_URL }}" }

[[services]]
name = "postgres"
type = "postgres"